FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

COPY Gateway.csproj .
RUN dotnet restore Gateway.csproj
COPY . .

ENTRYPOINT ["dotnet", "run", "--config", "Release", "--no-restore", "--project", "Gateway.csproj"]
